alias ll='ls -alF'
alias home='cd ~/Documents'
alias gb='git branch'
alias gd='git diff'
alias gs='git status'
alias gac='git add --all && git commit -m'
alias gp='git push'
alias py='python3'
alias pip='python3 -m pip'
alias vi='nvim'

